Repository GruppOne/project-docs, pull requests merged in 2020-06, with the labels that each got.

#280 docs: Aggiornamento Manuale Utente
  esterni/manuale-manutentore/components/introduzione.tex
  esterni/manuale-utente/components/glossario.tex
  esterni/manuale-utente/components/img/mobile-app/collegamentoldap.jpg
  esterni/manuale-utente/components/img/mobile-app/pagina-di-accesso.jpg
  esterni/manuale-utente/components/img/mobile-app/pagina-di-registrazione.jpg
  esterni/manuale-utente/components/img/mobile-app/pagina-organizzazioni.jpg
  esterni/manuale-utente/components/img/mobile-app/paginaconnesse.jpg
  esterni/manuale-utente/components/img/mobile-app/paginareportutente.jpg
  esterni/manuale-utente/components/img/mobile-app/selezionamentoorganizzazionepubblica.jpg
  esterni/manuale-utente/components/img/web-app/create-organization/create-organization-3b.png
  esterni/manuale-utente/components/img/web-app/edit-organization/3-configurazione-ldap.png
  esterni/manuale-utente/components/img/web-app/visualizza-dettagli-organizzazione-1.jpg
  esterni/manuale-utente/components/img/web-app/visualizza-dettagli-organizzazione-2.jpg
  esterni/manuale-utente/components/img/web-app/visualizza-dettagli-organizzazione.PNG
  esterni/manuale-utente/components/img/web-app/visualizza-profilo-personale.PNG
  esterni/manuale-utente/components/img/web-app/visualizza-profilo-personale.jpg
  esterni/manuale-utente/components/img/web-app/visualizza-report-organizzazione-1.jpg
  esterni/manuale-utente/components/img/web-app/visualizza-report-organizzazione-2.jpg
  esterni/manuale-utente/components/img/web-app/visualizza-report-utente.jpg
  esterni/manuale-utente/components/img/web-app/visualizza-utenti.jpg
  esterni/manuale-utente/components/mobile-application.tex
  esterni/manuale-utente/components/web-application.tex
Labels: docs - MU

#278 docs: Correzioni NdP
  interni/norme-di-progetto/components/processi-di-supporto/documentazione.tex
  interni/norme-di-progetto/components/processi-di-supporto/gestione-della-configurazione.tex
  interni/norme-di-progetto/components/processi-di-supporto/revisione.tex
  interni/norme-di-progetto/components/processi-di-supporto/risoluzione-dei-problemi.tex
  interni/norme-di-progetto/components/processi-di-supporto/verifica.tex
  interni/norme-di-progetto/components/processi-organizzativi/formazione-del-personale.tex
  interni/norme-di-progetto/components/processi-organizzativi/gestione-dei-rischi.tex
  interni/norme-di-progetto/components/processi-organizzativi/gestione-di-processo.tex
  interni/norme-di-progetto/components/processi-primari/sviluppo.tex
  interni/norme-di-progetto/norme-di-progetto.tex
Labels: docs - NdP

#259 docs: Verbali
  .mailmap
  esterni/verbali/verbale-esterno_2019-12-16.tex
  esterni/verbali/verbale-esterno_2020-01-09.tex
  esterni/verbali/verbale-esterno_2020-03-02.tex
  esterni/verbali/verbale-esterno_2020-03-09.tex
  esterni/verbali/verbale-esterno_2020-03-11.tex
  esterni/verbali/verbale-esterno_2020-05-05.tex
  esterni/verbali/verbale-esterno_2020-05-20.tex
  esterni/verbali/verbale-esterno_2020-06-16.tex
  interni/verbali/verbale-interno_2020-03-11.tex
  interni/verbali/verbale-interno_2020-03-17.tex
  interni/verbali/verbale-interno_2020-04-20.tex
  interni/verbali/verbale-interno_2020-04-27.tex
  interni/verbali/verbale-interno_2020-05-11.tex
  interni/verbali/verbale-interno_2020-05-19.tex
  interni/verbali/verbale-interno_2020-05-25.tex
  interni/verbali/verbale-interno_2020-06-01.tex
  interni/verbali/verbale-interno_2020-06-08.tex
Labels: docs - Verbali

#281 docs: Correzioni Manuale Manutentore
  esterni/manuale-manutentore/components/architettura/architettura-mobile-app.tex
  esterni/manuale-manutentore/components/architettura/architettura-server.tex
  esterni/manuale-manutentore/components/architettura/architettura-web-app.tex
  esterni/manuale-manutentore/components/architettura/img/webapp-auth.png
  esterni/manuale-manutentore/components/architettura/img/webapp-http-calls-services.png
  esterni/manuale-manutentore/components/architettura/img/webapp-loginservice.png
  esterni/manuale-manutentore/components/architettura/img/webapp-organization-builder.png
  esterni/manuale-manutentore/components/architettura/img/webapp-organization.png
  esterni/manuale-manutentore/components/architettura/img/webapp-package-diagram.png
  esterni/manuale-manutentore/components/architettura/img/webapp-place-builder.png
  esterni/manuale-manutentore/components/architettura/img/webapp-place.png
  esterni/manuale-manutentore/components/architettura/img/webapp-user-builder.png
  esterni/manuale-manutentore/components/glossario.tex
  esterni/manuale-manutentore/components/installazione/mobile-app.tex
  esterni/manuale-manutentore/components/installazione/server.tex
  esterni/manuale-manutentore/components/sezione-test.tex
  esterni/manuale-manutentore/components/tecnologie-interessate/librerie.tex
  esterni/manuale-manutentore/components/tecnologie-interessate/strumenti.tex
  esterni/manuale-manutentore/manuale-manutentore.tex
  esterni/verbali/verbale-esterno_2020-01-13.tex
  esterni/verbali/verbale-esterno_2020-02-17.tex
  esterni/verbali/verbale-esterno_2020-02-25.tex
  esterni/verbali/verbale-esterno_2020-03-09.tex
  esterni/verbali/verbale-esterno_2020-03-11.tex
  esterni/verbali/verbale-esterno_2020-04-02.tex
Labels: docs - MS

#284 Aggiornamento pdp
  esterni/piano-di-progetto/components/analisi-dei-rischi.tex
  esterni/piano-di-progetto/components/attualizzazione-dei-rischi.tex
  esterni/piano-di-progetto/components/consuntivo-di-periodo.tex
  esterni/piano-di-progetto/components/preventivo-a-finire.tex
  esterni/piano-di-progetto/components/riepilogo.tex
  esterni/piano-di-progetto/piano-di-progetto.tex
Labels: docs - PdP

#279 docs: Correzioni PdQ
  commons/img/bug_rilevati.png
  commons/img/code_coverage.png
  commons/img/code_smell.png
  commons/img/compl_ciclomatica.png
  commons/img/correttezzaortografica-RA.png
  commons/img/discostamenti-orari-economici.png
  commons/img/duplicazione_codice.png
  commons/img/indice_gulpease.png
  commons/img/percentualemetricheottimali.png
  commons/img/rischi_non_preventivati.png
  commons/img/tempo_stimato_bug.png
  commons/img/test_non_passati.png
  commons/img/test_passati.png
  esterni/piano-di-qualifica/components/qualita-di-processo.tex
  esterni/piano-di-qualifica/components/qualita-di-prodotto.tex
  esterni/piano-di-qualifica/components/report-verifica.tex
  esterni/piano-di-qualifica/components/specifica-test.tex
  esterni/piano-di-qualifica/components/tests/test-di-accettazione.tex
  esterni/piano-di-qualifica/components/tests/test-di-sistema.tex
  esterni/piano-di-qualifica/components/tests/test-di-unita.tex
  esterni/piano-di-qualifica/components/valutazioni-miglioramento.tex
  esterni/piano-di-qualifica/piano-di-qualifica.tex
Labels: docs - PdQ
