Repository GruppOne/project-docs, pull requests merged in 2020-04, with the labels that each got.

#168 Continuazione correzione Norme di progetto
  commons/config.tex
  esterni/piano-di-progetto/components/pianificazione.tex
  esterni/piano-di-qualifica/components/introduzione.tex
  esterni/piano-di-qualifica/piano-di-qualifica.tex
  interni/norme-di-progetto/components/introduzione.tex
  interni/norme-di-progetto/components/processi-di-supporto.tex
  interni/norme-di-progetto/components/processi-di-supporto/accertamento-della-qualita.tex
  interni/norme-di-progetto/components/processi-di-supporto/documentazione.tex
  interni/norme-di-progetto/components/processi-di-supporto/gestione-della-configurazione.tex
  interni/norme-di-progetto/components/processi-di-supporto/revisione.tex
  interni/norme-di-progetto/components/processi-di-supporto/risoluzione-dei-problemi.tex
  interni/norme-di-progetto/components/processi-di-supporto/validazione.tex
  interni/norme-di-progetto/components/processi-di-supporto/verifica.tex
  interni/norme-di-progetto/components/processi-organizzativi.tex
  interni/norme-di-progetto/components/processi-organizzativi/formazione-del-personale.tex
  interni/norme-di-progetto/components/processi-organizzativi/gestione-dei-rischi.tex
  interni/norme-di-progetto/components/processi-organizzativi/gestione-di-processo.tex
  interni/norme-di-progetto/components/processi-organizzativi/miglioramento-del-processo.tex
  interni/norme-di-progetto/components/processi-primari/fornitura.tex
  interni/norme-di-progetto/components/processi-primari/sviluppo.tex
  interni/norme-di-progetto/norme-di-progetto.tex
Labels: docs - NdP, feedback RR, problem, urgent

#199 Verbali della fase di progettazione architetturale
  esterni/verbali/verbale-esterno_2020-04-02.tex
  interni/verbali/verbale-interno_2020-03-30.tex
  interni/verbali/verbale-interno_2020-04-07.tex
Labels: documentation, feat

#173 Continuazione correzioni trasversali
  .chktexrc
  .mailmap
  .vscode/extensions.json
  .vscode/settings.json
  .vscode/tasks.json
  commons/config.tex
  commons/glossario.json
  commons/template.tex
  esterni/analisi-dei-requisiti/components/introduzione.tex
  esterni/glossario/glossario.tex
  esterni/piano-di-progetto/components/attualizzazione-dei-rischi.tex
  esterni/piano-di-progetto/components/consuntivo-di-periodo.tex
  esterni/piano-di-progetto/components/introduzione.tex
  esterni/piano-di-progetto/components/organigramma.tex
  esterni/piano-di-progetto/components/pianificazione.tex
  esterni/piano-di-progetto/components/preventivo.tex
  esterni/piano-di-qualifica/components/introduzione.tex
  esterni/piano-di-qualifica/components/qualita-di-prodotto.tex
  esterni/verbali/verbale-esterno_2020-02-17.tex
  esterni/verbali/verbale-esterno_2020-02-25.tex
  esterni/verbali/verbale-esterno_2020-03-09.tex
  esterni/verbali/verbale-esterno_2020-03-11.tex
  interni/norme-di-progetto/components/introduzione.tex
  interni/norme-di-progetto/components/processi-di-supporto.tex
  interni/norme-di-progetto/components/processi-organizzativi/formazione-del-personale.tex
  interni/norme-di-progetto/components/processi-primari.tex
  interni/norme-di-progetto/components/processi-primari/sviluppo.tex
  interni/studio-di-fattibilita/components/fattibilita-c1.tex
  interni/studio-di-fattibilita/components/fattibilita-c4.tex
  interni/studio-di-fattibilita/components/fattibilita-c5.tex
  interni/verbali/verbale-interno_2020-01-03.tex
  lettera-di-presentazione/lettera-di-presentazione.tex
Labels: documentation, problem

#163 Correzione Piano di Qualifica
  .github/workflows/check-files.yml
  .github/workflows/documentation.yml
  .github/workflows/project-management.yml
  commons/img/correttezzaortografica-RP.png
  commons/img/correttezzaortografica-RR.png
  commons/img/discostamenti-orari-economici.png
  commons/img/gulpease-RP.png
  commons/img/gulpease-RR.png
  commons/img/gulpease-conf.png
  commons/img/percentualemetricheottimali.png
  commons/template.tex
  esterni/piano-di-progetto/components/analisi-dei-rischi.tex
  esterni/piano-di-progetto/components/attualizzazione-dei-rischi.tex
  esterni/piano-di-progetto/components/consuntivo-di-periodo.tex
  esterni/piano-di-qualifica/components/qualita-di-processo.tex
  esterni/piano-di-qualifica/components/qualita-di-prodotto.tex
  esterni/piano-di-qualifica/components/report-verifica.tex
  esterni/piano-di-qualifica/components/specifica-test.tex
  esterni/piano-di-qualifica/components/tabella-metriche.tex
  esterni/piano-di-qualifica/components/valutazioni-miglioramento.tex
  esterni/piano-di-qualifica/piano-di-qualifica.tex
Labels: docs - PdQ

#204 Correzioni finali per la RP
  .gitignore
  .pwsh/Invoke-LocalChktexAction.ps1
  .pwsh/Remove-LatexGeneratedFiles.ps1
  .pwsh/release-compiler/Build-Release.ps1
  .pwsh/release-compiler/Stop-BuildRelease.ps1
  commons/img/discostamenti-orari-economici.png
  commons/template.tex
  esterni/analisi-dei-requisiti/analisi-dei-requisiti.tex
  esterni/analisi-dei-requisiti/components/requisiti.tex
  esterni/glossario/glossario.tex
  esterni/piano-di-progetto/components/analisi-dei-rischi.tex
  esterni/piano-di-progetto/components/attualizzazione-dei-rischi.tex
  esterni/piano-di-progetto/components/consuntivo-di-periodo.tex
  esterni/piano-di-progetto/components/preventivo-a-finire.tex
  esterni/piano-di-progetto/piano-di-progetto.tex
  esterni/piano-di-qualifica/components/qualita-di-processo.tex
  esterni/piano-di-qualifica/components/qualita-di-prodotto.tex
  esterni/piano-di-qualifica/components/report-verifica.tex
  esterni/piano-di-qualifica/components/specifica-test.tex
  esterni/piano-di-qualifica/components/tabella-metriche.tex
  esterni/piano-di-qualifica/components/valutazioni-miglioramento.tex
  esterni/piano-di-qualifica/piano-di-qualifica.tex
  esterni/verbali/verbale-esterno_2020-02-25.tex
  esterni/verbali/verbale-esterno_2020-04-02.tex
  interni/norme-di-progetto/components/processi-di-supporto/documentazione.tex
  interni/norme-di-progetto/components/processi-di-supporto/gestione-della-configurazione.tex
  interni/norme-di-progetto/components/processi-di-supporto/validazione.tex
  interni/norme-di-progetto/components/processi-organizzativi/gestione-di-processo.tex
  interni/norme-di-progetto/components/processi-primari/sviluppo.tex
  interni/norme-di-progetto/norme-di-progetto.tex
  interni/studio-di-fattibilita/studio-di-fattibilita.tex
  interni/verbali/verbale-interno_2020-02-25.tex
  interni/verbali/verbale-interno_2020-03-17.tex
  interni/verbali/verbale-interno_2020-03-24.tex
  interni/verbali/verbale-interno_2020-03-30.tex
  lettera-di-presentazione/lettera-di-presentazione.tex
Labels: documentation, problem, urgent
