Repository GruppOne/project-docs, pull requests merged in 2020-03, with the labels that each got.

#162 Aggiornamenti Glossario
  .github/workflows/conventional-commits.yml
  commons/glossario.json
  commons/template.tex
  esterni/glossario/glossario.tex
  esterni/piano-di-progetto/components/pianificazione.tex
  esterni/piano-di-progetto/piano-di-progetto.tex
Labels: docs - Glossario

#157 Verbali incontri esterni per PoC
  .chktexrc
  commons/config.tex
  esterni/verbali/verbale-esterno_2019-12-16.tex
  esterni/verbali/verbale-esterno_2020-01-09.tex
  esterni/verbali/verbale-esterno_2020-01-13.tex
  esterni/verbali/verbale-esterno_2020-02-17.tex
  esterni/verbali/verbale-esterno_2020-02-25.tex
  esterni/verbali/verbale-esterno_2020-03-02.tex
  interni/verbali/verbale-interno_2019-11-22.tex
  interni/verbali/verbale-interno_2019-11-28.tex
  interni/verbali/verbale-interno_2019-12-20.tex
  interni/verbali/verbale-interno_2020-01-03.tex
  interni/verbali/verbale-interno_2020-02-25.tex
Labels: documentation

#147 Correzione Analisi dei Requisiti
  .chktexrc
  .gitignore
  commons/config.tex
  commons/template.tex
  esterni/analisi-dei-requisiti/.gitignore
  esterni/analisi-dei-requisiti/README.md
  esterni/analisi-dei-requisiti/analisi-dei-requisiti.tex
  esterni/analisi-dei-requisiti/components/casi-duso-app.tex
  esterni/analisi-dei-requisiti/components/casi-duso-web-app.tex
  esterni/analisi-dei-requisiti/components/casi-duso.tex
  esterni/analisi-dei-requisiti/components/casi-duso/app/autenticazione.tex
  esterni/analisi-dei-requisiti/components/casi-duso/app/collegamento-organizzazione.tex
  esterni/analisi-dei-requisiti/components/casi-duso/app/diagrams/autenticazione-ldap-organizzazione.pu
  esterni/analisi-dei-requisiti/components/casi-duso/app/diagrams/autenticazione.pu
  esterni/analisi-dei-requisiti/components/casi-duso/app/diagrams/collegamento-organizzazione.pu
  esterni/analisi-dei-requisiti/components/casi-duso/app/diagrams/disconnessione-utente.pu
  esterni/analisi-dei-requisiti/components/casi-duso/app/diagrams/eliminazione-account.pu
  esterni/analisi-dei-requisiti/components/casi-duso/app/diagrams/gestione-lista-organizzazioni.pu
  esterni/analisi-dei-requisiti/components/casi-duso/app/diagrams/passaggio-noto-incognito.pu
  esterni/analisi-dei-requisiti/components/casi-duso/app/diagrams/recupero-credenziali.pu
  esterni/analisi-dei-requisiti/components/casi-duso/app/diagrams/registrazione.pu
  esterni/analisi-dei-requisiti/components/casi-duso/app/diagrams/scollegamento-organizzazione.pu
  esterni/analisi-dei-requisiti/components/casi-duso/app/diagrams/storico-utente.pu
  esterni/analisi-dei-requisiti/components/casi-duso/app/diagrams/visualizzazione-tempo-trascorso-nell-organizzazione-corrente.pu
  esterni/analisi-dei-requisiti/components/casi-duso/app/disconnessione-utente.tex
  esterni/analisi-dei-requisiti/components/casi-duso/app/eliminazione-account.tex
  esterni/analisi-dei-requisiti/components/casi-duso/app/gestione-lista-organizzazioni.tex
  esterni/analisi-dei-requisiti/components/casi-duso/app/passaggio-noto-incognito.tex
  esterni/analisi-dei-requisiti/components/casi-duso/app/recupero-credenziali.tex
  esterni/analisi-dei-requisiti/components/casi-duso/app/registrazione.tex
  esterni/analisi-dei-requisiti/components/casi-duso/app/scollegamento-organizzazione.tex
  esterni/analisi-dei-requisiti/components/casi-duso/app/storico-utente.tex
  esterni/analisi-dei-requisiti/components/casi-duso/app/visualizzazione-errore-rete-mancante.tex
  esterni/analisi-dei-requisiti/components/casi-duso/app/visualizzazione-tempo-trascorso-nell-organizzazione-corrente.tex
  esterni/analisi-dei-requisiti/components/casi-duso/web-app/aggiunta-gestore.tex
  esterni/analisi-dei-requisiti/components/casi-duso/web-app/aggiunta-visualizzatore.tex
  esterni/analisi-dei-requisiti/components/casi-duso/web-app/autenticazione.tex
  esterni/analisi-dei-requisiti/components/casi-duso/web-app/cessione-proprieta-organizzazione.tex
  esterni/analisi-dei-requisiti/components/casi-duso/web-app/creazione-owner.tex
  esterni/analisi-dei-requisiti/components/casi-duso/web-app/diagrams/eliminazione-account-wa.pu
  esterni/analisi-dei-requisiti/components/casi-duso/web-app/diagrams/gestione-luoghi.pu
  esterni/analisi-dei-requisiti/components/casi-duso/web-app/diagrams/gestione-organizzazione.pu
  esterni/analisi-dei-requisiti/components/casi-duso/web-app/diagrams/query-sul-dipendente.pu
  esterni/analisi-dei-requisiti/components/casi-duso/web-app/diagrams/query-sull-organizzazione.pu
  esterni/analisi-dei-requisiti/components/casi-duso/web-app/disconnessione.tex
  esterni/analisi-dei-requisiti/components/casi-duso/web-app/eliminazione-account.tex
  esterni/analisi-dei-requisiti/components/casi-duso/web-app/eliminazione-gestore.tex
  esterni/analisi-dei-requisiti/components/casi-duso/web-app/eliminazione-owner.tex
  esterni/analisi-dei-requisiti/components/casi-duso/web-app/eliminazione-visualizzatore.tex
  esterni/analisi-dei-requisiti/components/casi-duso/web-app/gestione-luoghi.tex
  esterni/analisi-dei-requisiti/components/casi-duso/web-app/gestione-organizzazione.tex
  esterni/analisi-dei-requisiti/components/casi-duso/web-app/query-sul-dipendente.tex
  esterni/analisi-dei-requisiti/components/casi-duso/web-app/query-sull-organizzazione.tex
  esterni/analisi-dei-requisiti/components/descrizione-generale.tex
  esterni/analisi-dei-requisiti/components/img/app_users.png
  esterni/analisi-dei-requisiti/components/img/web_users.png
  esterni/analisi-dei-requisiti/components/introduzione.tex
  esterni/analisi-dei-requisiti/components/requisiti.tex
Labels: change request, docs - AdR, feedback RR, problem

#153 Correzione e ristrutturazione Norme di Progetto
  .chktexrc
  .vscode/settings.json
  .vscode/snippets.code-snippets
  .vscode/tasks.json
  commons/style/class-diagrams.pu
  commons/template.tex
  interni/norme-di-progetto/components/img/aggregazione.png
  interni/norme-di-progetto/components/img/associazione.png
  interni/norme-di-progetto/components/img/attivita.png
  interni/norme-di-progetto/components/img/barre-attivazione.png
  interni/norme-di-progetto/components/img/class-example.png
  interni/norme-di-progetto/components/img/class_example.png
  interni/norme-di-progetto/components/img/composizione.png
  interni/norme-di-progetto/components/img/dipendenza.png
  interni/norme-di-progetto/components/img/ereditarieta.png
  interni/norme-di-progetto/components/img/example.png
  interni/norme-di-progetto/components/img/fork-e-join.png
  interni/norme-di-progetto/components/img/frame-interazione.png
  interni/norme-di-progetto/components/img/input.png
  interni/norme-di-progetto/components/img/merge.png
  interni/norme-di-progetto/components/img/nodo-di-branch.png
  interni/norme-di-progetto/components/img/nodo-di-merge.png
  interni/norme-di-progetto/components/img/nodo-finale.png
  interni/norme-di-progetto/components/img/nodo-iniziale.png
  interni/norme-di-progetto/components/img/output.png
  interni/norme-di-progetto/components/img/package.png
  interni/norme-di-progetto/components/img/sequenza.png
  interni/norme-di-progetto/components/img/signal.png
  interni/norme-di-progetto/components/img/swimlanes.png
  interni/norme-di-progetto/components/introduzione.tex
  interni/norme-di-progetto/components/processi-di-supporto.tex
  interni/norme-di-progetto/components/processi-di-supporto/accertamento-della-qualita.tex
  interni/norme-di-progetto/components/processi-di-supporto/documentazione.tex
  interni/norme-di-progetto/components/processi-di-supporto/gestione-della-configurazione.tex
  interni/norme-di-progetto/components/processi-di-supporto/risoluzione-dei-problemi.tex
  interni/norme-di-progetto/components/processi-di-supporto/validazione.tex
  interni/norme-di-progetto/components/processi-di-supporto/verifica.tex
  interni/norme-di-progetto/components/processi-organizzativi.tex
  interni/norme-di-progetto/components/processi-organizzativi/formazione-del-personale.tex
  interni/norme-di-progetto/components/processi-organizzativi/gestione-dei-rischi.tex
  interni/norme-di-progetto/components/processi-organizzativi/gestione-di-processo.tex
  interni/norme-di-progetto/components/processi-organizzativi/miglioramento-del-processo.tex
  interni/norme-di-progetto/components/processi-primari.tex
  interni/norme-di-progetto/components/processi-primari/fornitura.tex
  interni/norme-di-progetto/components/processi-primari/sviluppo.tex
  interni/norme-di-progetto/norme-di-progetto.tex
Labels: change request, docs - NdP, feedback RR, problem

#172 Aggiornamento lettera di presentazione
  lettera-di-presentazione/lettera-di-presentazione.tex
Labels: documentation

#169 Correzioni trasversali a vari documenti
  .gitignore
  README.md
  commons/template.tex
  esterni/analisi-dei-requisiti/analisi-dei-requisiti.tex
  esterni/analisi-dei-requisiti/components/requisiti.tex
  esterni/glossario/glossario.tex
  esterni/piano-di-progetto/components/analisi-dei-rischi.tex
  esterni/piano-di-progetto/components/attualizzazione-dei-rischi.tex
  esterni/piano-di-progetto/piano-di-progetto.tex
  esterni/piano-di-qualifica/piano-di-qualifica.tex
  interni/norme-di-progetto/norme-di-progetto.tex
  interni/studio-di-fattibilita/studio-di-fattibilita.tex
  lettera-di-presentazione/lettera-di-presentazione.tex
Labels: documentation

#171 Verbale call con committente del 09/03
  esterni/verbali/verbale-esterno_2020-03-09.tex
Labels: documentation

#176 Aggiunta verbali fase di progettazione
  .cz-config.js
  .czrc
  .editorconfig
  .github/workflows/latex.yml
  esterni/verbali/verbale-esterno_2020-03-11.tex
  interni/verbali/verbale-interno_2020-01-03.tex
  interni/verbali/verbale-interno_2020-02-25.tex
  interni/verbali/verbale-interno_2020-03-05.tex
  interni/verbali/verbale-interno_2020-03-11.tex
  interni/verbali/verbale-interno_2020-03-17.tex
  interni/verbali/verbale-interno_2020-03-24.tex
Labels: documentation
