Repository GruppOne/project-docs, pull requests merged in 2020-05, with the labels that each got.

#241 Sistema github action per i conventional commit
  .github/workflows/conventional-commits.yml
Labels: settings

#234 Manuale utente
  commons/config.tex
  commons/template.tex
  esterni/manuale-utente/components/glossario.tex
  esterni/manuale-utente/components/img/mobile-app/pagina-di-accesso.jpg
  esterni/manuale-utente/components/img/mobile-app/pagina-di-registrazione.jpg
  esterni/manuale-utente/components/img/web-app/accesso-web-app.png
  esterni/manuale-utente/components/img/web-app/create-organization/create-organization-1.png
  esterni/manuale-utente/components/img/web-app/create-organization/create-organization-2.png
  esterni/manuale-utente/components/img/web-app/create-organization/create-organization-3a.png
  esterni/manuale-utente/components/img/web-app/create-organization/create-organization-3b.png
  esterni/manuale-utente/components/img/web-app/create-organization/create-organization-4.png
  esterni/manuale-utente/components/img/web-app/edit-organization/1-dettagli-organizzazione.png
  esterni/manuale-utente/components/img/web-app/edit-organization/2-luoghi-organizzazione.png
  esterni/manuale-utente/components/img/web-app/edit-organization/3-configurazione-ldap.png
  esterni/manuale-utente/components/img/web-app/edit-organization/4-privilegi.png
  esterni/manuale-utente/components/img/web-app/edit-organization/5-conferma-modifiche.png
  esterni/manuale-utente/components/img/web-app/organizations-list.png
  esterni/manuale-utente/components/img/web-app/pagina-home.PNG
  esterni/manuale-utente/components/img/web-app/recupero-password.PNG
  esterni/manuale-utente/components/img/web-app/visualizza-dettagli-organizzazione.PNG
  esterni/manuale-utente/components/img/web-app/visualizza-profilo-personale.PNG
  esterni/manuale-utente/components/introduzione.tex
  esterni/manuale-utente/components/mobile-application.tex
  esterni/manuale-utente/components/supporto-tecnico.tex
  esterni/manuale-utente/components/web-application.tex
  esterni/manuale-utente/manuale-utente.tex
Labels: docs - MU

#240 Aggiunta verbali per recap incrementi
  esterni/verbali/verbale-esterno_2020-01-09.tex
  esterni/verbali/verbale-esterno_2020-01-13.tex
  esterni/verbali/verbale-esterno_2020-02-17.tex
  esterni/verbali/verbale-esterno_2020-02-25.tex
  esterni/verbali/verbale-esterno_2020-03-02.tex
  esterni/verbali/verbale-esterno_2020-03-11.tex
  esterni/verbali/verbale-esterno_2020-04-02.tex
  esterni/verbali/verbale-esterno_2020-05-05.tex
  interni/verbali/verbale-interno_2019-11-22.tex
  interni/verbali/verbale-interno_2019-11-28.tex
  interni/verbali/verbale-interno_2019-12-20.tex
  interni/verbali/verbale-interno_2020-01-03.tex
  interni/verbali/verbale-interno_2020-02-25.tex
  interni/verbali/verbale-interno_2020-03-05.tex
  interni/verbali/verbale-interno_2020-03-24.tex
  interni/verbali/verbale-interno_2020-03-30.tex
  interni/verbali/verbale-interno_2020-04-07.tex
  interni/verbali/verbale-interno_2020-04-13.tex
  interni/verbali/verbale-interno_2020-04-20.tex
  interni/verbali/verbale-interno_2020-04-27.tex
  interni/verbali/verbale-interno_2020-05-04.tex
Labels: docs - Verbali

#235 Correzione AdR
  commons/template.tex
  esterni/analisi-dei-requisiti/analisi-dei-requisiti.tex
  esterni/analisi-dei-requisiti/components/casi-duso/app/autenticazione.tex
  esterni/analisi-dei-requisiti/components/casi-duso/app/collegamento-organizzazione.tex
  esterni/analisi-dei-requisiti/components/casi-duso/app/diagrams/collegamento-organizzazione.pu
  esterni/analisi-dei-requisiti/components/casi-duso/app/diagrams/disconnessione-utente.pu
  esterni/analisi-dei-requisiti/components/casi-duso/app/diagrams/eliminazione-account.pu
  esterni/analisi-dei-requisiti/components/casi-duso/app/diagrams/gestione-lista-organizzazioni.pu
  esterni/analisi-dei-requisiti/components/casi-duso/app/diagrams/passaggio-noto-incognito.pu
  esterni/analisi-dei-requisiti/components/casi-duso/app/diagrams/recupero-credenziali.pu
  esterni/analisi-dei-requisiti/components/casi-duso/app/diagrams/registrazione.pu
  esterni/analisi-dei-requisiti/components/casi-duso/app/diagrams/scollegamento-organizzazione.pu
  esterni/analisi-dei-requisiti/components/casi-duso/app/diagrams/storico-utente.pu
  esterni/analisi-dei-requisiti/components/casi-duso/app/diagrams/visualizzazione-tempo-trascorso-nell-organizzazione-corrente.pu
  esterni/analisi-dei-requisiti/components/casi-duso/app/disconnessione-utente.tex
  esterni/analisi-dei-requisiti/components/casi-duso/app/eliminazione-account.tex
  esterni/analisi-dei-requisiti/components/casi-duso/app/gestione-lista-organizzazioni.tex
  esterni/analisi-dei-requisiti/components/casi-duso/app/passaggio-noto-incognito.tex
  esterni/analisi-dei-requisiti/components/casi-duso/app/registrazione.tex
  esterni/analisi-dei-requisiti/components/casi-duso/app/scollegamento-organizzazione.tex
  esterni/analisi-dei-requisiti/components/casi-duso/app/storico-utente.tex
  esterni/analisi-dei-requisiti/components/casi-duso/app/visualizzazione-errore-rete-mancante.tex
  esterni/analisi-dei-requisiti/components/casi-duso/app/visualizzazione-tempo-trascorso-nell-organizzazione-corrente.tex
  esterni/analisi-dei-requisiti/components/requisiti.tex
Labels: docs - AdR

#237 Correzione PdQ
  .vscode/settings.json
  .vscode/tasks.json
  commons/img/bug_rilevati.png
  commons/img/code_coverage.png
  commons/img/code_smell.png
  commons/img/compl_ciclomatica.png
  commons/img/correttezzaortografica-RP.png
  commons/img/correttezzaortografica-RQ.png
  commons/img/correttezzaortografica-RR.png
  commons/img/duplicazione_codice.png
  commons/img/gulpease-conf.png
  commons/img/indice_gulpease.png
  commons/img/rischi_non_preventivati.png
  commons/img/tempo_stimato_bug.png
  commons/img/test_non_passati.png
  commons/img/test_passati.png
  esterni/analisi-dei-requisiti/analisi-dei-requisiti.tex
  esterni/analisi-dei-requisiti/components/requisiti.tex
  esterni/glossario/glossario.tex
  esterni/manuale-manutentore/manuale-manutentore.tex
  esterni/manuale-utente/manuale-utente.tex
  esterni/piano-di-qualifica/components/qualita-di-processo.tex
  esterni/piano-di-qualifica/components/qualita-di-prodotto.tex
  esterni/piano-di-qualifica/components/report-verifica.tex
  esterni/piano-di-qualifica/components/specifica-test.tex
  esterni/piano-di-qualifica/components/tabella-metriche.tex
  esterni/piano-di-qualifica/components/tests/test-di-accettazione.tex
  esterni/piano-di-qualifica/components/tests/test-di-integrazione.tex
  esterni/piano-di-qualifica/components/tests/test-di-sistema.tex
  esterni/piano-di-qualifica/components/tests/test-di-unita.tex
  esterni/piano-di-qualifica/components/valutazioni-miglioramento.tex
  esterni/piano-di-qualifica/piano-di-qualifica.tex
Labels: docs - PdQ

#251 Aggiorna attualizzazione dei rischi, consuntivo e preventivo a finire nel PdP
  esterni/piano-di-progetto/components/attualizzazione-dei-rischi.tex
  esterni/piano-di-progetto/components/consuntivo-di-periodo.tex
  esterni/piano-di-progetto/components/introduzione.tex
  esterni/piano-di-progetto/components/preventivo-a-finire.tex
  esterni/piano-di-progetto/piano-di-progetto.tex
Labels: docs - PdP

#257 Ultime correzioni RQ
  .pwsh/release-compiler/Build-Release.ps1
  esterni/analisi-dei-requisiti/analisi-dei-requisiti.tex
  esterni/glossario/glossario.tex
  esterni/manuale-manutentore/components/glossario.tex
  esterni/manuale-utente/components/glossario.tex
  esterni/manuale-utente/components/web-application.tex
Labels: settings
